name: Run specs

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TZ: "Europe/Moscow"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install deps
        run: yarn install --immutable 
      - name: Run eslint
        run: yarn jslint
      - name: Run yarn audit
        run: |
          yarn audit